version: 2
plugins:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
  flog:
      enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
exclude_patterns:
 - typings
 - features/**/*
 - spec/**/*
 - test/**/*
 - vendor/**/*
 - lib/public
 - db/migrate
 - db/schema.rb
