Metrics/LineLength:
  Max: 140
Metrics/AbcSize:
  Max: 20
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'db/models/*'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
