Metrics/LineLength:
  Max: 140
Metrics/ModuleLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 30
Metrics/AbcSize:
  Max: 50
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'db/models/*'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
